"""Postgres 持久化层 —— Sprint 1。

职责:
- 提供 SQLAlchemy engine / session 工厂(惰性初始化, 无 POSTGRES_URL 时不连接)
- 定义 InterviewSession / EvaluationReport 的 ORM 模型
- 提供 schemas(pydantic) <-> ORM 的转换与读写接口

调用约定:
- 业务层(orchestrator/agents/api) 只 import repository 里的 save_*/load_*,
  不直接接触 SQLAlchemy session, 也不直接读 ORM 行。
- ORM 模型对业务不透明: 拿到的永远是 src.schemas 里的 pydantic 类型。

后续:
- Sprint 1 后期: 引入 Alembic 做 schema 演进(目前先用 metadata.create_all)
- Sprint 2: FastAPI 起来后再评估是否切 async engine
"""
from __future__ import annotations

from src.db.base import (
    DatabaseNotConfigured,
    get_engine,
    init_db,
    session_scope,
)
from src.db.repository import (
    approve_question_draft,
    bulk_approve_chunk,
    count_knowledge_chunks,
    count_question_drafts,
    delete_knowledge_chunks_for_dataset,
    delete_question_drafts_for_dataset,
    edit_question_draft,
    compose_question_topic,
    get_candidate_with_status,
    get_chunk_topic_for_draft,
    get_chunk_with_drafts,
    get_dataset,
    list_candidates_with_status_for_job,
    list_chunks_with_draft_stats,
    list_datasets,
    list_datasets_summary,
    list_knowledge_chunks,
    list_question_topics,
    map_draft_chunk_topics,
    list_skill_backlog,
    list_jobs,
    list_seed_questions,
    load_candidate,
    load_candidate_for_plan,
    load_job,
    load_latest_plan_for_candidate,
    load_plan,
    load_report,
    load_report_by_session,
    load_review_for_report,
    load_seed_question,
    load_session,
    load_user,
    load_user_by_username,
    record_skill_backlog,
    reject_question_draft,
    save_candidate,
    save_candidate_sections,
    save_job,
    save_plan,
    save_report,
    save_review_record,
    save_seed_question,
    save_session,
    save_user,
    upsert_dataset,
    upsert_knowledge_chunks,
    upsert_question_drafts,
)

__all__ = [
    "DatabaseNotConfigured",
    "get_engine",
    "init_db",
    "session_scope",
    "approve_question_draft",
    "bulk_approve_chunk",
    "count_knowledge_chunks",
    "count_question_drafts",
    "delete_knowledge_chunks_for_dataset",
    "delete_question_drafts_for_dataset",
    "edit_question_draft",
    "compose_question_topic",
    "get_candidate_with_status",
    "get_chunk_topic_for_draft",
    "get_chunk_with_drafts",
    "get_dataset",
    "list_candidates_with_status_for_job",
    "list_chunks_with_draft_stats",
    "list_datasets",
    "list_datasets_summary",
    "list_knowledge_chunks",
    "list_question_topics",
    "map_draft_chunk_topics",
    "list_skill_backlog",
    "list_jobs",
    "list_seed_questions",
    "load_candidate",
    "load_candidate_for_plan",
    "load_job",
    "load_latest_plan_for_candidate",
    "load_plan",
    "load_report",
    "load_report_by_session",
    "load_review_for_report",
    "load_seed_question",
    "load_session",
    "load_user",
    "load_user_by_username",
    "record_skill_backlog",
    "reject_question_draft",
    "save_candidate",
    "save_candidate_sections",
    "save_job",
    "save_plan",
    "save_report",
    "save_review_record",
    "save_seed_question",
    "save_session",
    "save_user",
    "upsert_dataset",
    "upsert_knowledge_chunks",
    "upsert_question_drafts",
]
